server:
    port: 8788

eureka:
    client:
        serviceUrl:
             defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fasah
    username:root
    password:12345
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
